#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "{{project-name | kebab_case}}"
version = "0.1.0"
description = "A scala-wasm health check API using Spin"

[[trigger.http]]
route = "/..."
component = "health"

[component.health]
source = "target/scala-2.13/{{project-name | kebab_case}}-fastopt/main.wasm"

[component.health.build]
command = "sbt --client fastLinkJS"
